{% set name = "proof" %}
{% set version = "0.3.0" %}
{% set compress_type = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_val = "dca8eddbdcad597f7109084143ffb1849d91c57bd0fe44aed8f3fb01f4af34b9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  {{ hash_type }}: {{ hash_val }}

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - pip
    - python

  run:
    - python
    - six >=1.6.1

test:
  imports:
    - proof

about:
  home: http://proof.readthedocs.org/
  license: MIT
  license_family: MIT
  # license_file: COPYING - no MANIFEST; see https://github.com/wireservice/proof/pull/18
  summary: 'A Python library for creating optimized, repeatable and self-documenting data analysis pipelines.'
  doc_url: http://proof.readthedocs.org/
  dev_url: https://github.com/wireservice/proof

extra:
  recipe-maintainers:
    - pmlandwehr
