{% set name = "proof" %}
{% set version = "0.4.0" %}
{% set compress_type = "tar.gz" %}
{% set hash_val = "20a1597a6ba5650c414bf47f3c9c0c18673f02498784c7e069b529f0fd549943" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  sha256: {{ hash_val }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - pip
    - python

  run:
    - python
    - six >=1.6.1

test:
  imports:
    - proof

about:
  home: http://proof.readthedocs.org/
  license: MIT
  license_file: COPYING
  license_family: MIT
  # license_file: COPYING - no MANIFEST; see https://github.com/wireservice/proof/pull/18
  summary: 'A Python library for creating optimized, repeatable and self-documenting data analysis pipelines.'
  doc_url: http://proof.readthedocs.org/
  dev_url: https://github.com/wireservice/proof

extra:
  recipe-maintainers:
    - pmlandwehr
