travis:
  secure:
    BINSTAR_TOKEN: EZNa2DGM/rOK9+HZHZsu2TH9HQ8aAX8Ei1ceai0ZofNK8bAGir9MmZjnHNIB07eztfKC7i8cVTjxK25jasVgezY4BTBxQ3JGymOOkkhLJjI6WNBgQH+Sp3K1Nhw4GNs2Xagon/EfzTN9uuoSAWA2rn4X+YThLnrF51u4inR9C5YmU3a45uqLzPKPSuDlxPaKskCmS+B5r/XY1chf7Azjq1nCntSgvRcJ9yi5GKZx1/+oHGgqgYv9zua3y3beMyCaKFkubjmpfHn0dO53G+D31CaKgitGTY6t4YeCh8eR7hqP3QnAi1GDcQoftytH4JFKyW5D9zD4ToGjUwXEI6XZpkVixCLgBKyQq/3gSCHUzL8Bw1gQzN08GGB4EH/xSXmHuSgGvKFy0bAUK8/AlTak+pfZW8PjUpK/qksjkEhZKKmltCNyxY8xoqAnT7Q6nmAQ02FJUAqerFE+BFprXeEPE+YL6E346MlYv7WwUMHZU3rJ19Dyj5Nhh+XcO7GH74E8xgUTIdpxfWmE18MMjU5GcTtgtHf+Tt1Ezr+A7B0ph7gcKttIfxYIFIgotCi6wTfw+m+tTPW9j5qFUYSO7Q9pJF0PVWxTnJoUZlVxKC33NP/f0lvwxTxh155DHA2Lv+8rK54C14g8XFVidl1nYdUTjIwIWKjW01dEo7CNHbevvUQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
