travis:
  secure:
    BINSTAR_TOKEN: lS9X9Fb8ExUuPUvycIdyGBMY81QSJUwQGCM7blto0pkA01gjHZa/OTda4z77GaJxgnw43J/+ErKTV3wnPHUxwrO9tIYihpudQ8/eSA1VvPnkpyvp3LCdSlX1VN4mwL58x3G8/np9DMLLPXh2Hay1D+kfMH8BFTlBe32ORnGAlFn3KnpWkNGs7TbpaGhfa6Lobx72djMwlBQlnYBl8R1DKa28/O4Dh1zuujFnVtVewDDJ291EgF/tUmaJ1yWv7eWMK0ucvCIJfm+2bbgsi8JbGAiTJF+3CMzK3b596c6NcIhhdSSqSBZYzo0TXecFLYJtyt2piZe41TXrbL0BVQxq0B7BbTkVplYmOGEqCW7HxQrjScfjFBnIACWA1VPhyKT0bMROQYAAx6iNAAnUMaWOx2pNeTIL6ZunxKrbu+/FU7NcQ8a51lfZ85MJIs3b/RO3kN8HVu5dY4WwAbFQpnmuyTI2mI/tVyMsmCJCz1ZZBHhv8e98xOOg4Pgb2bzVDWIbe/J8jNKWdDYkA3EiR1Nq7xTboSJwFNtXUZBBH9uCRWmlBMCJck8QmvYaYDXGO0Se/wB6E9TK81o3nbda4xcGfxzUmhfHdYhhJJIMwIj6Wd/NvCTDWRxqOXINqrXsP9ckcMUoWclFUh7sBhs5vpv7pTGYr1AA2HEVN8DWRuc8huo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
